apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: konflux-mrrc-help
spec:
  params:
    - name: dataJsonPath
      description: path to data json file
  steps:
    - name: show-konflux-mrrc-help
      image: quay.io/ligangty/charon:latest
      script: |
        set -eux
        echo "data: $(params.dataJsonPath)"
        cat $(params.dataJsonPath)
        charon --help
      workingDir: $(workspaces.data.path)
  workspaces:
    - name: data