apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: konflux-mrrc-help
spec:
  params:
    - name: productName
      type: string
      description: The name of the product
      default: "NoProduct"
    - name: productVersion
      type: string
      description: The version of the product
      default: "0"
  steps:
    - name: show-konflux-mrrc-help
      image: quay.io/ligangty/charon:latest
      script: |
        set -eux
        echo $(params.productName)
        echo $(params.productVersion)
        charon --help
      workingDir: $(workspaces.data.path)
  workspaces:
    - name: data