---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: publish-to-mrrc
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  params:
    - name: mrrcParamFilePath
      description: path of the env file for mrrc parameters to use
      type: string
    - name: cosignPubKeyConfig
      description: the configmap name for cosign verify public key
      type: string
    - name: charonAWSSecret
      description: the secret name for charon aws credential file
      type: string
  steps:
    - name: prepare-repo
      image: quay.io/konflux-ci/release-service-utils:4576e1e2a30439129cb69c8a4f39f7ced2d44376
      script: |
        set -eux

        # First, verify the maven zip artifact
        MRRC_FILE="$(workspaces.data.path)/$(params.mrrcParamFilePath)"
        . "$MRRC_FILE"
        echo "Verify the maven repo zip $MRRC_ZIP_REGISTRY"
        cosign verify --key /home/konflux/.cosign/cosign.pub $MRRC_ZIP_REGISTRY
        cosign verify-attestation --key /home/konflux/.cosign/cosign.pub $MRRC_ZIP_REGISTRY

        # Second, download the maven zip to local
        echo "Downloading the maven repo zip $MRRC_ZIP_REGISTRY"
        mrrc_dir="$(dirname $MRRC_FILE)/mrrc"
        mkdir $mrrc_dir
        cd $mrrc_dir
        oras pull $MRRC_ZIP_REGISTRY
      volumeMounts:
        - name: "pub-key-vol"
          mountPath: "/home/konflux/.cosign/"
    - name: upload-maven-repo
      image: quay.io/konflux-ci/charon:b99585182f6750b3f6352889fe9c2222b57833ef
      script: |
        set -eux
        MRRC_FILE="$(workspaces.data.path)/$(params.mrrcParamFilePath)"
        . "$MRRC_FILE"
        target=$MRRC_TARGET
        productName=$MRRC_PRODUCT_NAME
        productVersion=$MRRC_PRODUCT_VERSION
        work_dir="$(dirname $MRRC_FILE)/mrrc"
        mavenRepoPath="$(ls $work_dir/*.zip)"
        echo "Release $productName-$productVersion into $target"
        charon upload -p $productName -v $productVersion -t $target $mavenRepoPath
      volumeMounts:
        - name: "charon-configs-vol"
          mountPath: "/home/charon/.charon"
        - name: "charon-aws-vol"
          mountPath: "/home/charon/.aws"
  volumes:
    - name: "pub-key-vol"
      configMap:
        name: "$(params.cosignPubKeyConfig)"
    - name: "charon-configs-vol"
      configMap:
        name: "charon-configs"
    - name: "charon-aws-vol"
      secret:
        secretName: "$(params.charonAWSSecret)"
  workspaces:
    - name: data
