apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: konflux-mrrc-repo-sign-verify
spec:
  params:
    - name: mrrcEnvFilePath
      description: path to mrrc env file
    - name: pubKeyVol
      description: the secret mount volume name for cosign verify pub key
      type: string
      default: "pubKeyVol"
    - name: pubKeyFile
      type: string
      default: "cosign.pub"
    - name: pubKey
      type: string
      default: "test-cosign-pub-key"
  steps:
    - name: verify-repo-signature
      image: registry.redhat.io/rhtas/cosign-rhel9:1.0.1 
      script: |
        set -eux
        source $(params.mrrcEnvFilePath)
        echo "Verify the maven repo zip $MRRC_ZIP_REGISTRY"
        cosign verify --key /home/konflux/.cosign/$(params.pubKeyFile) $MRRC_ZIP_REGISTRY
      workingDir: $(workspaces.data.path)
      volumeMounts:
        - name: "$(params.pubKey)"
          mountPath: "/home/konflux/.cosign/"
  volumes:
    - name: "$(params.pubKey)"
      secret:
        secretName: "$(params.pubKey)"
  workspaces:
    - name: data