apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: konflux-mrrc-repo-dowload
spec:
  params:
    - name: dataJsonPath
      description: path to data json file
    - name: repoStorePath
      description: path to store the repo zip
  results:
    - name: repoPath
      description: path of the maven repo zip downloaded
  steps:
    - name: download-maven-repo
      image: quay.io/konflux-ci/oras:latest
      script: |
        set -eux
        jsonData=$(cat $(params.dataJsonPath))
        zipRegistry=$(echo $jsonData | jq -r '.product.zipRegistry')
        echo "Downloading the maven repo zip $(zipRegistry) to $(params.repoStorePath)"
        cd $(params.repoStorePath)
        mkdir maven-repo
        cd maven-repo
        oras pull $zipRegistry
        repoName=$(ls *.zip)
        echo -n "maven-repo/$repoName" > "$(results.repoPath.path)"
      workingDir: $(workspaces.data.path)
  workspaces:
    - name: data