---
apiVersion: v1
kind: ConfigMap
metadata:
  name: charon-configs
  labels:
    app: konflux-mrrc-release
data:
  charon.yaml: >
    #aws_profile: ${profile}
    #aws_cf_enable: True

    ignore_patterns:
      - ".*^(redhat).*"
      - ".*snapshot.*"

    ignore_signature_suffix:
      maven:
        - ".sha1"
        - ".sha256"
        - ".md5"
        - "maven-metadata.xml"
        - "archtype-catalog.xml"
      npm:
        - "package.json"

    #detach_signature_command: "rpm-sign --detach-sign --key {{ key }} {{ file }}"

    targets:
      dev-maven-ga:
      - bucket: "dev-maven-bucket"
        prefix: ga
      dev-maven-ea:
      - bucket: "dev-maven-bucket"
        prefix: earlyaccess/all
      dev-npm:
      - bucket: "dev-npm-npmjs-bucket"
        prefix: /
