apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: konflux-mrrc-release
  labels:
    release.appstudio.openshift.io/auto-release: "true"
spec:
  applications:
    - konflux-mrrc-release
  environment: konflux-mrrc-release
  origin: gli2-tenant
  policy: konflux-mrrc-release-policy
  data:
    releaseNotes:
      product_name: "activemq"
      product_version: "0.0.1"
    mrrc:
      release: ga
      environment: dev
      awsSecret: charon-aws-credentials
      charonConfig: |-
        aws_profile: ronda
        aws_cf_enable: False
        ignore_patterns:
          - '\..+'
          - 'index\.htm?'
          - 'JBossEULA.*'
          - 'example-settings.xml.*'
          - 'versions.txt.*'
          - 'maven-metadata-local.xml'
          - '.*\.asc'
        targets:
          dev-maven-ga:
          - bucket: "dev-maven-bucket"
            prefix: ga
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/ligangty/konflux-mrrc-release.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: "release/pipelines/mrrc-release-pipeline.yaml"
    timeouts:
      pipeline: "1h0m0s"
    serviceAccountName: appstudio-pipeline
