apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: konflux-mrrc-release
  labels:
    release.appstudio.openshift.io/auto-release: "true"
spec:
  applications:
    - konflux-mrrc-release
  environment: konflux-mrrc-release
  origin: gli2-tenant
  policy: konflux-mrrc-release-policy
  data:
    mrrc:
      product:
        name: "activemq"
        cosignPubKeyConfig: "cosign-pub-key"
      release: ga
      environment: dev
      awsSecret: charon-aws-credentials
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/ligangty/konflux-mrrc-release.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: "release/pipelines/mrrc-release-pipeline.yaml"
    timeouts:
      pipeline: "1h0m0s"
    serviceAccountName: appstudio-pipeline
