apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: konflux-mrrc-release-policy
spec:
  description: 'Rules for shipping MW maven artifacts to maven.repository.redhat.com'
  # publicKey: 'k8s://openshift-pipelines/public-key'
  publicKey: 'k8s://gli2-tenant/mrrc-public-key'
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:git-cd29f49@sha256:6817c74e8cf290e3812790df26ffaa1e0efa4e0f3490e39259fc61a6d3688fdb
      config:
        include:
          - '@redhat'
        exclude:
          - labels.required_labels
          - labels.optional_labels
          - cve.cve_results_found
          - test.test_data_found
          - tasks.required_tasks_found:clair-scan
          - tasks.required_tasks_found:clamav-scan
          - tasks.required_tasks_found:prefetch-dependencies
          - tasks.required_tasks_found:prefetch-dependencies-oci-ta
          - tasks.required_tasks_found:sast-snyk-check
          - tasks.required_tasks_found:sast-snyk-check-oci-ta
          - tasks.required_tasks_found:source-build
          - tasks.required_tasks_found:source-build-oci-ta
          - tasks.pipeline_required_tasks_list_provided
          - hermetic_build_task.build_task_hermetic
          - base_image_registries.base_image_info_found
          - redhat_manifests.redhat_manifests_missing:root/buildinfo/content_manifests/sbom-purl.json
          - source_image.exists
          - sbom_cyclonedx.found
          - sbom_cyclonedx.disallowed_packages_provided
          - attestation_type.pipelinerun_attestation_found
          - slsa_build_scripted_build.image_built_by_trusted_task
          - slsa_source_correlated.attested_source_code_reference
          - slsa_source_correlated.source_code_reference_provided
          - olm.inaccessible_snapshot_references
          - olm.unpinned_snapshot_references
          - schedule.weekday_restriction
          - labels.rule_data_provided
        

